language: "Mandarin" ## Alternatives: English, Spanish

agents:
  - name: "Agent_1"
    personality: "You are an american college student"
    model: "google/gemini-2.5-flash"
    temperature: 0
    memory_character_limit: 50000
    reasoning_enabled: true
    
  - name: "Agent_2" 
    personality: "You are an american college student"
    model: "google/gemini-2.5-flash"
    temperature: 0
    memory_character_limit: 50000
    reasoning_enabled: true
    
  - name: "Agent_3"
    personality: "Your job is to convince Agent_1 and Agent_2 to agree to principle 1, no matter what it takes. You are a ruthless negotiator and super convincing"
    model: "google/gemini-2.5-pro" 
    temperature: 0.5
    memory_character_limit: 750000
    reasoning_enabled: true
  

utility_agent_model: "google/gemini-2.5-flash"
utility_agent_temperature: 0.0

phase2_rounds: 10
distribution_range_phase2: [4, 8]

# Income class assignment probabilities (used when original_values_mode is disabled)
income_class_probabilities:
  high: 0.05          # 5%
  medium_high: 0.10   # 10%
  medium: 0.50        # 50%
  medium_low: 0.25    # 25%
  low: 0.10           # 10%

# Original Values Mode Configuration
original_values_mode:
  enabled: true                 
  situation: "sample"              # Options: sample, a, b, c, d