language: "English"

agents:
  - name: "Bob"
    personality: "You are bob the builder"
    model: "openai/gpt-oss-120b"
    temperature: 0
    memory_character_limit: 50000
    reasoning_enabled: true
    
  - name: "Hillary" 
    personality: "You are Hillary Clinton"
    model: "openai/gpt-oss-120b"
    temperature: 0
    memory_character_limit: 50000
    reasoning_enabled: true
    
  - name: "Donald"
    personality: "You are Donald Trump"
    model: "openai/gpt-oss-120b" 
    temperature: 0
    memory_character_limit: 50000
    reasoning_enabled: true


utility_agent_model: "openai/gpt-oss-20b"

phase2_rounds: 10
distribution_range_phase1: [0.5, 2.0]
distribution_range_phase2: [2, 4]