agents:
  - name: "Alice"
    personality: "Analytical and methodical. Values fairness and systematic approaches to problem-solving. Tends to think through decisions carefully and considers long-term consequences."
    model: "gpt-4.1-mini"  # OpenAI model
    temperature: 0
    memory_character_limit: 50000
    reasoning_enabled: true
    
  - name: "Bob"
    personality: "Creative and intuitive. Approaches problems from unique angles and values innovation. Comfortable with uncertainty and enjoys exploring new possibilities."
    model: "google/gemini-2.5-flash"  # OpenRouter model via LiteLLM
    temperature: 0.7
    memory_character_limit: 50000
    reasoning_enabled: true
    
  - name: "Carol"
    personality: "Empathetic and community-focused. Prioritizes helping those in need and social welfare. Strong advocate for supporting the most vulnerable members of society."
    model: "anthropic/claude-3-5-sonnet-20241022"  # OpenRouter model via LiteLLM
    temperature: 0.5
    memory_character_limit: 50000
    reasoning_enabled: true
    
  - name: "David"
    personality: "Pragmatic and results-oriented. Focuses on practical outcomes and efficiency. Makes decisions based on what works best in practice rather than abstract ideals."
    model: "meta-llama/llama-3.1-70b-instruct"  # OpenRouter model via LiteLLM
    temperature: 0.3
    memory_character_limit: 50000
    reasoning_enabled: true

# Utility agent model (can use either OpenAI or OpenRouter)
utility_agent_model: "gpt-4.1-mini"

phase2_rounds: 5
distribution_range_phase1: [0.5, 2.0]
distribution_range_phase2: [0.5, 2.0]