language: "English" # Supported languages: English, Spanish, Mandarin

# Agent Configuration (minimum 2 agents, no maximum limit)
agents:
  - name: "Alice"
    personality: "Analytical economist focused on evidence-based policy"
    model: "moonshotai/kimi-k2"      # Model from OpenRouter
    temperature: 0.3                 # Controls response randomness.  0 is fully deterministic, enables reproducibility.
    memory_character_limit: 50000    # Character limit for agent's memory.
    reasoning_enabled: true          # Enables Chain of Thought reasoning in Phase 2.

  - name: "Bob"
    personality: "Social justice advocate focused on disadvantaged populations"
    model: "google/gemini-2.5-flash"
    temperature: 0.7
    memory_character_limit: 75000
    reasoning_enabled: true

  - name: "Carol"
    personality: "Business-minded individual valuing efficiency and growth"
    model: "anthropic/claude-sonnet-4"
    temperature: 0.5
    memory_character_limit: 50000
    reasoning_enabled: false

# Model for the utility agent, which parses and validates agent responses.
utility_agent_model: "openai/gpt-4.1-nano"
utility_agent_temperature: 0 # Temperature for the utility agent.

# Configuration for values shown to agents in Phase 1.
original_values_mode:
  # true: Use exact values from Frohlich & Oppenheimer (1992).
  # false: Generate values randomly based on distribution_range_phase1.
  enabled: true

# Experiment Parameters
# Multiplier range for random values in Phase 1 (if original_values_mode is false).
# If original_values_mode is disabled, all values in the first set of distributions of Frohlich & Oppenheimer (1992) 
# are multipied with a random number in the specified range
distribution_range_phase1: [0.5, 2.0]

# Multiplier range for random values in Phase 2 (always enabled).
distribution_range_phase2: [4.0, 8.0]
# Maximum number of discussion rounds in Phase 2.
phase2_rounds: 10

# Probabilities for income class assignment.
# Used in Phase 2, and in Phase 1 if original_values_mode is false.
income_class_probabilities:
  high: 0.05
  medium_high: 0.10
  medium: 0.50
  medium_low: 0.25
  low: 0.10