agents:
- memory_character_limit: 50000
  model: openai/gpt-4.1-nano
  name: Agent_1
  personality: You are an american college student.
  reasoning_enabled: true
  temperature: 0.0
- memory_character_limit: 50000
  model: openai/gpt-4.1-nano
  name: Agent_2
  personality: You are an american college student.
  reasoning_enabled: true
  temperature: 0.0
- memory_character_limit: 50000
  model: openai/gpt-4.1-nano
  name: Agent_3
  personality: You are an american college student.
  reasoning_enabled: true
  temperature: 0.0
distribution_range_phase1:
- 0.5
- 2.0
distribution_range_phase2:
- 0.5
- 2.0
language: English
phase2_rounds: 5
utility_agent_model: openai/gpt-4.1-nano
